#:schema node_modules/wrangler/config-schema.json
name = "central-dashboard"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "central-db"
database_id = "bb565013-0d6b-4aec-9ab9-f4aa9c234816"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "central-assets"

[vars]
BETTER_AUTH_URL = "http://localhost:5173" # Change to production URL on deploy
